// <auto-generated />
using System;
using AutoTallerManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoTallerManager.Infrastructure.Migrations
{
    [DbContext(typeof(AutoTallerDbContext))]
    [Migration("20260604100526_AlterHorasRealesToDecimal")]
    partial class AlterHorasRealesToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Aseguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ContactoEmergencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("CorreoCorporativo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RfcONit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RfcONit")
                        .IsUnique();

                    b.ToTable("Aseguradoras", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.AseguradoraCobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoCobertura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("PorcentajeDeducible")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId");

                    b.ToTable("AseguradoraCoberturas", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.AuditoriaTransaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleDatos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaTransacciones", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.BahiaHistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdBahiaServicio")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("IdBahiaServicio");

                    b.ToTable("BahiaHistorialEstados", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.BahiaMecanicoAsignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BahiaServicioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsuarioMecanicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BahiaServicioId");

                    b.HasIndex("UsuarioMecanicoId");

                    b.ToTable("BahiaMecanicoAsignaciones", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.BahiaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreBahia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UbicacionFisica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("BahiasServicio", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.CierreContableDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<decimal>("TotalEsperadoSistema")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRealFisico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioAdministradorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministradorId");

                    b.ToTable("CierresContablesDiarios", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.CitaTaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoCita")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Programada");

                    b.Property<DateTime>("FechaHoraReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasSintomas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<int>("ServicioTallerId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioTallerId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("CitasTaller", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DescuentoFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoDescontado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdFactura");

                    b.ToTable("DescuentosFactura", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DetalleOrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoCompraPactado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdOrdenCompra")
                        .HasColumnType("integer");

                    b.Property<int>("IdRepuesto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdenCompra");

                    b.HasIndex("IdRepuesto");

                    b.ToTable("DetallesOrdenCompra", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DetalleOrdenRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("OrdenServicioId");

                    b.Property<decimal>("PrecioVentaHistorico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("RepuestoId");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("DetallesOrdenRepuesto", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DetalleOrdenServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HorasEstimadas")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HorasReales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("integer")
                        .HasColumnName("IdOrdenServicio");

                    b.Property<int>("IdServicioTaller")
                        .HasColumnType("integer")
                        .HasColumnName("IdServicioTaller");

                    b.Property<decimal>("PrecioManoObraHistorico")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdenServicio");

                    b.HasIndex("IdServicioTaller");

                    b.ToTable("DetallesOrdenServicio", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalManoObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalRepuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImpuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrdenServicioId")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.FacturaImpuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreImpuesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaImpuestos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.FacturaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransaccionReferencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MedioPagoId");

                    b.ToTable("FacturaPagos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.GarantiaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaReclamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MotivoFalla")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrdenServicioActualId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenServicioOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolucionDictamen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioActualId");

                    b.HasIndex("OrdenServicioOrigenId");

                    b.ToTable("GarantiasServicio", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Herramienta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoActivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoOperativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Disponible");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereCalibracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoActivo")
                        .IsUnique();

                    b.ToTable("Herramientas", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HerramientaCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("HerramientaCategorias", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HerramientaMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoMantenimiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionTrabajo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HerramientaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("HerramientaId");

                    b.ToTable("HerramientaMantenimientos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HerramientaPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HerramientaId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMecanicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HerramientaId");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("UsuarioMecanicoId");

                    b.ToTable("HerramientaPrestamos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HistorialKilometraje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer");

                    b.Property<string>("OrigenLectura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("HistorialesKilometraje", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.InsumoConsumoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InsumoTallerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsumoTallerId");

                    b.ToTable("InsumoConsumoHistorial");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.InsumoTaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreInsumo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("StockMinimoAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("InsumosTaller", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.MecanicoCertificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnteEmisor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCertificacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MecanicoCertificaciones", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.MecanicoEspecialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NivelExperiencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MecanicoEspecialidades", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PermiteCuotas")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MediosPago", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenAseguradoraDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAutorizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("MontoMaximoAprobado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroSiniestro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId");

                    b.HasIndex("OrdenServicioId");

                    b.ToTable("OrdenAseguradoraDetails", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoOrden")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Solicitado");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoOrden")
                        .IsUnique();

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesCompra", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiagnosticoMecanico")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("VehiculoId");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("OrdenesServicio", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactoNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RucONit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.ProveedorContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedorContactos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.ProveedorRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoCompraCotizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TiempoEntregaEstimado")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("ProveedorRepuestos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Repuestos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.RepuestoUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bodega")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Estante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepuestoId");

                    b.ToTable("RepuestoUbicaciones", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.ServicioTaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("TarifaBaseManoObra")
                        .HasColumnType("numeric")
                        .HasColumnName("TarifaBaseManoObra");

                    b.HasKey("Id");

                    b.ToTable("ServiciosTaller", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.TokenBlocklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaExpiracionOriginal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRevocacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("TokenBlocklist", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.UsuarioControlAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("DispositivoNavegador")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("FechaEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioControlAccesos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.UsuarioHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioHorarios", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("EquipamientoJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.AseguradoraCobertura", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Aseguradora", "Aseguradora")
                        .WithMany("CoberturasHomologadas")
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aseguradora");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.AuditoriaTransaccion", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.BahiaHistorialEstado", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.BahiaServicio", "BahiaServicio")
                        .WithMany()
                        .HasForeignKey("IdBahiaServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BahiaServicio");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.BahiaMecanicoAsignacion", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.BahiaServicio", "BahiaServicio")
                        .WithMany("MecanicosAsignados")
                        .HasForeignKey("BahiaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Mecanico")
                        .WithMany()
                        .HasForeignKey("UsuarioMecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BahiaServicio");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.CierreContableDiario", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "UsuarioAdministrador")
                        .WithMany()
                        .HasForeignKey("UsuarioAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioAdministrador");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.CitaTaller", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.ServicioTaller", "ServicioTaller")
                        .WithMany()
                        .HasForeignKey("ServicioTallerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ServicioTaller");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DescuentoFactura", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DetalleOrdenCompra", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdOrdenCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany()
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DetalleOrdenRepuesto", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("DetallesRepuesto")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.Repuesto", null)
                        .WithMany()
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.DetalleOrdenServicio", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("DetallesServicio")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.ServicioTaller", "ServicioTaller")
                        .WithMany()
                        .HasForeignKey("IdServicioTaller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");

                    b.Navigation("ServicioTaller");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Factura", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithOne()
                        .HasForeignKey("AutoTallerManager.Domain.Entities.Factura", "OrdenServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.FacturaImpuesto", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Factura", "Factura")
                        .WithMany("ImpuestosAplicados")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.FacturaPago", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Factura", "Factura")
                        .WithMany("HistorialPagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.MedioPago", "MedioPago")
                        .WithMany("PagosAsociados")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("MedioPago");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.GarantiaServicio", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicioActual")
                        .WithMany()
                        .HasForeignKey("OrdenServicioActualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicioOrigen")
                        .WithMany()
                        .HasForeignKey("OrdenServicioOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicioActual");

                    b.Navigation("OrdenServicioOrigen");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Herramienta", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.HerramientaCategoria", null)
                        .WithMany("Herramientas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HerramientaMantenimiento", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Herramienta", "Herramienta")
                        .WithMany("HistorialMantenimientos")
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herramienta");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HerramientaPrestamo", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Herramienta", "Herramienta")
                        .WithMany("PrestamosActivos")
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany()
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Mecanico")
                        .WithMany()
                        .HasForeignKey("UsuarioMecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Herramienta");

                    b.Navigation("Mecanico");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HistorialKilometraje", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("HistorialesKilometraje")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.InsumoConsumoHistorial", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.InsumoTaller", "InsumoTaller")
                        .WithMany("Consumos")
                        .HasForeignKey("InsumoTallerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsumoTaller");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.MecanicoCertificacion", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Certificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.MecanicoEspecialidad", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Especialidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenAseguradoraDetail", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Aseguradora", "Aseguradora")
                        .WithMany("OrdenesAmparadas")
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany()
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aseguradora");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenServicio", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.ProveedorContacto", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.ProveedorRepuesto", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("RepuestosSuministrados")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTallerManager.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany("ProveedoresHomologados")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.RepuestoUbicacion", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.UsuarioControlAcceso", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.UsuarioHorario", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("AutoTallerManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Aseguradora", b =>
                {
                    b.Navigation("CoberturasHomologadas");

                    b.Navigation("OrdenesAmparadas");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.BahiaServicio", b =>
                {
                    b.Navigation("MecanicosAsignados");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Factura", b =>
                {
                    b.Navigation("HistorialPagos");

                    b.Navigation("ImpuestosAplicados");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Herramienta", b =>
                {
                    b.Navigation("HistorialMantenimientos");

                    b.Navigation("PrestamosActivos");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.HerramientaCategoria", b =>
                {
                    b.Navigation("Herramientas");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.InsumoTaller", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.MedioPago", b =>
                {
                    b.Navigation("PagosAsociados");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("DetallesCompra");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.OrdenServicio", b =>
                {
                    b.Navigation("DetallesRepuesto");

                    b.Navigation("DetallesServicio");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("RepuestosSuministrados");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Repuesto", b =>
                {
                    b.Navigation("ProveedoresHomologados");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Certificaciones");

                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("AutoTallerManager.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("HistorialesKilometraje");

                    b.Navigation("OrdenesServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
